# Aliases
alias clean-aurutils-cache='find ~/.cache/aurutils/sync -type d -name .git -execdir git clean -xi \;'
alias config='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias fastfetch='hyfetch'
alias ls='eza --icons --group-directories-first'
alias mutt='bash -c "pushd ~/Downloads > /dev/null; mutt; popd > /dev/null"'
alias rm='rm -I'
alias sort='sort -n'
alias ssh='kitten ssh'
alias sudo='sudo '
alias trayer='trayer -l --edge top --align right --SetDockType true --SetPartialStrut true --expand true --widthtype request --transparent true --tint 0x232634 --height 18 --monitor 0'
alias trc='trash-empty'
alias trl='trash-list'
alias trm='trash-rm'
alias trp='trash-put'
alias trr='trash-restore'
alias vi='vim'
