directory: ~/Music
library: ~/Music/musiclibrary.db
plugins: inline edit fetchart embedart mbsync albumtypes smartplaylist lyrics the info autobpm lastimport types ftintitle scrub fuzzy chroma limit
format_item: %the{$artist} - %the{$album} ($original_year)$atypes - %the{$title}
format_album: %the{$albumartist} - %the{$album} ($original_year)$atypes
sort_item: artist+ original_year+ original_month+ album+ disc+ track+
sort_album: albumartist+ original_year+ original_month+ album+
original_date: yes
item_fields:
  multidisc: 1 if disctotal > 1 else 0
import:
  move: yes
  timid: yes
paths:
  default: $albumartist/[$original_year]$atypes $album%aunique{}/%if{$multidisc,$disc-}$track $title
musicbrainz:
  searchlimit: 10
fetchart:
  cautious: yes
  minwidth: 250
  maxwidth: 1000
  enforce_ratio: 1%
  sources: filesystem wikipedia coverart amazon albumart
embedart:
  auto: no
  remove_art_file: yes
smartplaylist:
  relative_to: ~/Music
  playlist_dir: ~/.config/mpd/playlists
  playlists:
    - name: Metal_Before_90s.m3u
      query: 'genre:Metal original_year:..1989'
    - name: 90s_Power_Metal.m3u
      query: 'genre:"Power Metal" original_year:1990..1999'
    - name: 2000plus_Power_Metal.m3u
      query: 'genre:"Power Metal" original_year:2000..'
    - name: Symphonic_Metal.m3u
      query: 'genre:"Symphonic Metal"'
    - name: Gothic_Metal.m3u
      query: 'genre:"Gothic Metal"'
    - name: 90s_Black_Metal.m3u
      query: 'genre:"Black Metal" original_year:1990..1999'
    - name: Symphonic_and_Melodic_Black.m3u
      query: ['genre:"Symphonic Black Metal"', 'genre:"Melodic Black Metal"']
the:
  patterns: ^Il\s ^La\s ^Lo\s ^Gli\s ^Le\s
ftintitle:
  drop: yes
scrub:
  auto: no
fuzzy:
  threshold: 0.8
chroma:
  auto: no
include: [ lyrics.yaml, lastfm.yaml ]
